{
 "title": "immich",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Immich version",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "immich_version_number{version=\"1.50.1\"}",
     "legendFormat": "{{version}}"
    }
   ]
  },
  {
   "title": "user count",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "immich_user_count", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "disk space used by Immich",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(immich_usage_by_user)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "total disk size",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "immich_totalDiskSize{}", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "total disk size usage",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "immich_diskUse{}", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "remaining disk size",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "immich_diskUsagePercentage", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "usage in GB",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "immich_usage_by_user", "legendFormat": "{{firstName}}" }
   ]
  },
  {
   "title": "Photos",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "immich_photos_by_user", "legendFormat": "{{firstName}}" }
   ]
  },
  {
   "title": "videos",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "immich_videos_by_user", "legendFormat": "{{firstName}}" }
   ]
  },
  {
   "title": "Photos Growth",
   "type": "timeseries",
   "description": "amount of photos over time",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
   "targets": [
    {
     "expr": "immich_photos_by_user{job=\"prometheus\"}",
     "legendFormat": "{{firstName}}"
    }
   ]
  },
  {
   "title": "Videos growth",
   "type": "timeseries",
   "description": "amount of videos over time",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 13 },
   "targets": [
    { "expr": "immich_videos_by_user ", "legendFormat": "{{firstName}}" }
   ]
  }
 ]
}